"""
thread_generator.py
────────────────────
Main orchestrator: combines website + Twitter/X research
then generates contest-winner style threads via Groq.
"""

import os
import re
import json
import logging
import asyncio
import aiohttp
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from typing import Optional

from twitter_scraper import TwitterScraper
from ai_providers import generate_with_fallback, get_available_providers, PROVIDERS
from brand_analyzer import BrandAnalyzer

logger = logging.getLogger(__name__)

# ════════════════════════════════════════════════════════════════════
# CRAFT REFERENCE — Not a template, but an example of living writing
# ════════════════════════════════════════════════════════════════════

CRAFT_REFERENCE = """
This is an example of a contest-winning thread. Read it like a writer reading a masterpiece —
pay attention to WHY each sentence works, not WHAT it says.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REFERENCE THREAD (Fontana Ecosystem)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1/8
One of the biggest problems in crypto today is that many tokens don't actually do anything meaningful.

• You buy.
• You hold.
• You hope the price goes up.

That's usually the entire experience.

There's little participation, limited ecosystem growth, and no strong reason to stay engaged beyond speculation. Creating fragile communities built around price movements instead of real utility overtime.

@FontanaEcoTem takes a different approach.

Instead of launching a token first and figuring out utility later, Fontana is building an ecosystem designed around participation from the start. The idea is simple: the more you engage, the more value is created.

Went through their whitepaper, roadmap, and Twitter — a few things became clear.

Fontana is trying to build a self-sustaining digital economy that connects crypto activity, virtual economies, and real-world value.

Stay w me ✍🏿...

---
2/8
At the center of Fontana is a three-layer economic structure.

Rather than relying on one token to do everything, Fontana separates value across three distinct assets — each with a different job.

• Realityverse Points (RVP) — connects crypto activity to real-world rewards.
• LUMINA — powers the internal virtual economy inside Lumeria.
• Cerulean Sovereign Token — ultra-scarce, long-term governance layer.

This matters more than it sounds.

Most projects fail exactly here. They build one token, assign it ten jobs, and watch it collapse under its own weight. Fontana designs for separation of concerns from day one.

Less speculation. More economic flow.

---
3/8
RVP might be the most interesting piece.

It's not a governance token. Not a reward point you'll never use. It's a mechanism to connect what happens on-chain to what happens in real life.

Users earn RVP through buying activity. Those points then unlock:

• Flight tickets
• Holiday packages  
• Physical goods
• Real-world experiences

The bridge between crypto and daily life is one of the hardest problems in this space. Most projects talk about it. Fontana is building the actual infrastructure for it.

That's a different conversation entirely.

---
4/8
Then there's LUMINA — the currency inside Fontana's virtual world, Lumeria.

Here's the part that caught my attention.

LUMINA isn't generated by buying. It's generated by *selling*, project participation, and ecosystem engagement. So instead of selling being an exit, it feeds back into the economy.

People use LUMINA for trading, gaming, avatar customization, P2P transactions inside Lumeria.

And when LUMINA gets spent on purchases — it burns.

Permanently.

Controlling inflation without constant manual intervention is something most token economies never figure out. This does it by design.

---
5/8
The third layer is Cerulean — Fontana's governance token. But not governance as you know it.

Most governance tokens are just purchased votes. Whoever buys the most, decides the most. It concentrates power instead of distributing it.

Cerulean Dust is earned, not bought. Through:

• Buying and selling activity
• Holding
• Social engagement  
• Participating inside Lumeria

This shifts who gets influence. Not the richest wallets. The most active builders and contributors.

It's a subtle design choice. But it changes everything about how the community forms.

---
6/8
There's also an economic tax mechanism — and before you scroll past that, hear me out.

These aren't extractive taxes. Every fee collected gets redistributed:

• Back into rewards pools
• Into development funding
• Used for buybacks
• Burned to reduce supply
• Allocated to Cerulean vault reserves

Activity generates fees. Fees fund growth. Growth pulls in more participants. More participants generate more activity.

That's the flywheel. And it's baked into the architecture, not bolted on later.

---
7/8
One feature I didn't expect: the Automated Recoil Mechanism.

When heavy selling pressure pushes the price down sharply, the protocol responds automatically:

• Temporary taxes activate on sells
• Buyback mechanisms trigger
• Sell pressure absorbs into the system

The goal isn't to prevent price from ever falling. It's to stop panic from becoming a death spiral.

Markets crash because fear compounds fear. A system that self-corrects under pressure is rare. Most projects react manually — too slow, too late.

Whether this executes perfectly in practice is worth watching. But the design intent is clear: stability over volatility.

---
8/8
The roadmap runs across 7+ years. Five phases. Token launch to global adoption.

I'll be honest — long roadmaps can be theater. Anyone can write a five-year plan.

What's different here is the sequencing makes sense. Foundation first, then utility, then metaverse, then governance, then scale. Each phase builds on the last.

The Twitter activity reflects this too — consistent communication, no sudden pivots, clear focus on ecosystem building over price action.

That's the thread.

Fontana isn't trying to be another token you hold and forget. It's trying to build an economy you participate in.

Whether it gets there is an open question. But the structure is one of the more thoughtful I've read.

Website: fontanaeco.io | X: @FontanaEcoTem
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NOTES FOR THE WRITER — what makes this thread work:

1. THE OPENER IS NOT ABOUT THE PROJECT. The first sentence is about an industry problem the reader feels themselves.
   Effect: the reader feels understood before being offered a solution.

2. SHORT SENTENCES ARE NOT A STYLISTIC TRICK — THEY ARE CONFIDENCE.
   Insecure writers write long to sound smart.
   Confident writers write short because they know the point is strong.
   "Permanently." stands alone. One word. One punch.

3. EVERY TWEET HOLDS ONE SURPRISE.
   A twist, insight, or unexpected framing. The reader doesn't know what's coming next.
   This is what keeps people from stopping their scroll.

4. SKEPTICISM IS BUILT INTO THE WRITING.
   "Long roadmaps can be theater. Anyone can write a five-year plan."
   The writer acknowledges the weakness BEFORE the reader thinks of it. This builds trust.

5. FACTS ARE ALLOWED TO SPEAK FOR THEMSELVES.
   No "this is amazing!" — there's a description of the mechanism, then "That's a different conversation entirely."
   The judgment comes from the reader, not the writer.

6. TWITTER DATA IS WOVEN INTO THE NARRATIVE, NOT REPORTED.
   Not: "They have 10k followers."
   But: "Twitter activity reflects this — consistent communication, no sudden pivots."
   Twitter data becomes evidence of the project's character.

7. THE CLOSING IS HONEST, NOT HYPE.
   "Whether it gets there is an open question."
   This is precisely what's most convincing. The reader knows the writer wasn't paid.
"""

VOICE_PRINCIPLES = """
WRITER'S VOICE PRINCIPLES — INTERNALIZE THESE:

YOUR VOICE IS: An independent analyst who just spent three hours reading docs, whitepapers, and scrolling a project's Twitter.
You're excited because you found something genuinely interesting — not because you were paid.
You're skeptical enough to be honest, open enough to be impressed.

HOW TO THINK BEFORE WRITING EACH TWEET:
→ "What is the single most non-obvious insight from this section?"
→ "How do I frame this so the reader thinks: 'oh, I never thought about it that way'?"
→ "Is there an interesting tension, paradox, or irony here?"
→ "What closing line will make the reader immediately scroll to the next tweet?"

WHAT KILLS GOOD WRITING:
- Adjectives without evidence: "powerful", "innovative", "groundbreaking" — without showing why
- Generic transition sentences: "Furthermore,", "Additionally,", "In conclusion,"
- Explaining the obvious: if the reader can predict the next sentence, delete it
- Hype that won't acknowledge risk: looks like PR, not analysis
- Bullet points that could be sentences: use bullets ONLY when a list is genuinely a list

WHAT MAKES WRITING COME ALIVE:
- Reframing something familiar in a new way
- Acknowledging weaknesses or uncertainty honestly — then continuing the analysis
- Sentences that start with a verb or concrete subject, not an abstraction
- "Zoom out" moments that give broader context, then "zoom in" to a specific detail
- Tweet closers that feel like a conclusion discovered, not declared
"""


# ════════════════════════════════════════════════════════════════════
# WEB SCRAPER
# ════════════════════════════════════════════════════════════════════
class WebScraper:
    def __init__(self):
        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        }
        self.priority_paths = [
            "whitepaper", "litepaper", "docs", "documentation", "about",
            "how-it-works", "how", "learn", "technology", "tech", "features",
            "ecosystem", "tokenomics", "token", "roadmap", "vision", "solution",
        ]

    async def fetch(self, url: str, session: aiohttp.ClientSession) -> Optional[str]:
        try:
            async with session.get(
                url, headers=self.headers,
                timeout=aiohttp.ClientTimeout(total=18),
                ssl=False, allow_redirects=True,
            ) as r:
                return await r.text(errors="ignore") if r.status == 200 else None
        except Exception as e:
            logger.warning(f"Fetch failed {url}: {e}")
            return None

    def extract(self, html: str, url: str) -> dict:
        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "iframe",
                          "noscript", "aside", "form", "button", "header"]):
            tag.decompose()

        # Title
        title = ""
        for og in [("property", "og:title"), ("name", "twitter:title")]:
            m = soup.find("meta", attrs={og[0]: og[1]})
            if m and m.get("content"):
                title = m["content"]; break
        if not title and soup.title:
            title = (soup.title.string or "").strip()
        if not title:
            h = soup.find("h1")
            if h: title = h.get_text(strip=True)

        # Description
        desc = ""
        for og in [("property", "og:description"), ("name", "description"),
                   ("name", "twitter:description")]:
            m = soup.find("meta", attrs={og[0]: og[1]})
            if m and m.get("content"):
                desc = m["content"]; break

        km = soup.find("meta", attrs={"name": "keywords"})
        keywords = km["content"] if km and km.get("content") else ""

        headings = [f"[{t.name.upper()}] {t.get_text(strip=True)}"
                    for t in soup.find_all(["h1","h2","h3","h4"])
                    if 3 < len(t.get_text(strip=True)) < 200]

        paragraphs = [p.get_text(strip=True) for p in soup.find_all("p")
                      if len(p.get_text(strip=True)) > 40]

        list_items = [li.get_text(strip=True) for li in soup.find_all("li")
                      if 20 < len(li.get_text(strip=True)) < 600]

        extra = []
        for el in soup.find_all(["div","section","article"]):
            cls = " ".join(el.get("class", []))
            eid = el.get("id", "")
            combined = (cls + " " + eid).lower()
            if any(k in combined for k in ["feature","about","how","token",
                                            "ecosystem","roadmap","benefit","why","vision"]):
                t = el.get_text(separator=" ", strip=True)
                if len(t) > 80:
                    extra.append(t[:800])

        domain = urlparse(url).netloc
        seen = set()
        links = []
        for a in soup.find_all("a", href=True):
            full = urljoin(url, a["href"])
            p = urlparse(full)
            if p.netloc == domain and full not in seen:
                path = p.path.lower()
                if any(k in path for k in self.priority_paths):
                    links.append({"url": full, "text": a.get_text(strip=True)})
                    seen.add(full)

        socials = []
        for a in soup.find_all("a", href=True):
            href = a["href"]
            if any(s in href for s in ["twitter.com","x.com","t.me","discord","telegram"]):
                socials.append(href)

        # Auto-detect Twitter handle from social links
        twitter_handle = None
        for s in socials:
            m = re.search(r"(?:twitter\.com|x\.com)/([A-Za-z0-9_]+)", s)
            if m and m.group(1).lower() not in ["share","intent","home","search"]:
                twitter_handle = m.group(1)
                break

        return {
            "title": title, "description": desc, "keywords": keywords,
            "headings": headings[:35], "paragraphs": paragraphs[:25],
            "list_items": list_items[:30], "extra_content": extra[:5],
            "internal_links": links[:8], "social_links": socials[:5],
            "twitter_handle": twitter_handle,
        }

    async def deep_scrape(self, base_url: str) -> dict:
        result = {"main_url": base_url, "pages": [], "twitter_handle": None}

        async with aiohttp.ClientSession() as session:
            html = await self.fetch(base_url, session)
            if not html:
                return result

            main = self.extract(html, base_url)
            main["url"] = base_url
            main["page_type"] = "main"
            main["raw_html"] = html  # for brand analysis
            result["pages"].append(main)

            # Capture Twitter handle from main page
            if main.get("twitter_handle"):
                result["twitter_handle"] = main["twitter_handle"]

            scraped = 0
            seen_urls = {base_url}

            for link in main.get("internal_links", [])[:5]:
                if scraped >= 4:
                    break
                lurl = link["url"]
                if lurl in seen_urls:
                    continue
                await asyncio.sleep(0.4)
                sh = await self.fetch(lurl, session)
                if sh:
                    sd = self.extract(sh, lurl)
                    sd["url"] = lurl
                    sd["page_type"] = "sub"
                    result["pages"].append(sd)
                    seen_urls.add(lurl)
                    scraped += 1
                    if sd.get("twitter_handle") and not result["twitter_handle"]:
                        result["twitter_handle"] = sd["twitter_handle"]

            # Fallback common paths
            if scraped < 2:
                parsed = urlparse(base_url)
                base = f"{parsed.scheme}://{parsed.netloc}"
                for path in ["/about","/docs","/whitepaper","/how-it-works",
                              "/technology","/ecosystem","/tokenomics","/litepaper"]:
                    if scraped >= 4:
                        break
                    cand = base + path
                    if cand in seen_urls:
                        continue
                    await asyncio.sleep(0.4)
                    ch = await self.fetch(cand, session)
                    if ch:
                        cd = self.extract(ch, cand)
                        cd["url"] = cand
                        cd["page_type"] = "fallback"
                        result["pages"].append(cd)
                        seen_urls.add(cand)
                        scraped += 1

        return result


# ════════════════════════════════════════════════════════════════════
# THREAD GENERATOR (ORCHESTRATOR)
# ════════════════════════════════════════════════════════════════════
class ThreadGenerator:
    def __init__(self):
        # Validate that at least one provider is available
        available = get_available_providers()
        if not available:
            raise ValueError(
                "No API keys configured. "
                "Set at least one in .env: GROQ_API_KEY, DEEPSEEK_API_KEY, or OPENAI_API_KEY"
            )
        self.web_scraper = WebScraper()
        self.twitter_scraper = TwitterScraper()
        self.brand_analyzer = BrandAnalyzer()

    # ── Compile website research ──────────────────────────────────
    def compile_web_research(self, data: dict) -> str:
        parts = []
        for page in data.get("pages", []):
            ltype = {"main":"MAIN PAGE","sub":"SUB-PAGE",
                     "fallback":"COMMON PATH"}.get(page.get("page_type",""),"PAGE")
            parts.append(f"\n{'='*55}\n{ltype}: {page.get('url','')}\n{'='*55}")

            for key, label in [("title","TITLE"),("description","DESCRIPTION"),("keywords","KEYWORDS")]:
                if page.get(key):
                    parts.append(f"{label}: {page[key]}")

            if page.get("social_links"):
                parts.append(f"SOCIAL LINKS: {', '.join(page['social_links'][:4])}")

            if page.get("headings"):
                parts.append("\nPAGE STRUCTURE:")
                parts.extend(page["headings"][:20])

            if page.get("paragraphs"):
                parts.append("\nPARAGRAPH CONTENT:")
                for p in page["paragraphs"][:15]:
                    parts.append(f"  → {p[:400]}")

            if page.get("list_items"):
                parts.append("\nFEATURES / KEY POINTS:")
                for li in page["list_items"][:20]:
                    parts.append(f"  • {li[:300]}")

            if page.get("extra_content"):
                parts.append("\nSPECIAL SECTIONS:")
                for ec in page["extra_content"]:
                    parts.append(f"  [{ec[:500]}]")

        return "\n".join(parts)

    # ── Build prompt ──────────────────────────────────────────────
    def create_prompt(self, web_research: str, twitter_research: str,
                      url: str, twitter_handle: str, lang: str,
                      brand_profile: str = "") -> str:

        if lang == "indonesia":
            lang_directive = (
                "Write in genuinely natural Bahasa Indonesia — like someone "
                "who is smart and well-read, not a translation from English. "
                "Keep crypto/web3 technical terms in English. "
                "Avoid literal translations that feel stiff."
            )
        else:
            lang_directive = (
                "Write in English — not formal English, but the English of someone smart "
                "who reads a lot and talks like a real person."
            )

        twitter_block = (
            f"TWITTER/X DATA (@{twitter_handle}):\n{twitter_research}\n\n"
            "Use Twitter data as evidence of the project's character, not a report. "
            "Communication tone, posting consistency, types of announcements — "
            "all of it reveals who this team actually is."
            if twitter_research and twitter_handle
            else "Twitter: not available. Focus on website research."
        )

        # ── Inject brand persona into writer identity ──────
        if brand_profile:
            persona_block = f"""
━━━ WHO YOU ARE WHILE WRITING THIS ━━━

{brand_profile}

IMPORTANT — these are not style instructions, this is the character you embody:
→ The unique perspective and hook style above are your ENTRY POINT into the writing
→ The brand vocabulary is already in your head — use it naturally, don't force it
→ The project's colors and visual identity are real — let the nuance seep into your word choices
→ If this brand is "rebellious", don't write like a prospectus
→ If this brand is "institutional", don't write like a crypto influencer
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        else:
            persona_block = ""

        return f"""You are a thread writer who wins contests not because of formulas — but because you write like a human who genuinely cares about what you're writing.

{CRAFT_REFERENCE}

{VOICE_PRINCIPLES}
{persona_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TASK: Write a thread about → {url}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WEBSITE RESEARCH DATA:
{web_research}

{twitter_block}

LANGUAGE: {lang_directive}

━━━ THINKING PROCESS BEFORE WRITING ━━━

Do this mentally, in this order:

1. FIND THE CORE TENSION
   Every interesting project lives at the intersection of two things that seem to contradict each other.
   Example: "decentralized" but needs governance. "Simple" but the tech is complex.
   Find that tension — that's where compelling threads are born.

2. LOOK FOR THE NON-OBVIOUS INSIGHT
   What would most people miss if they only read the headline?
   What small detail actually reveals a bigger philosophy?
   Build the thread from there.

3. WRITE THE CLOSING FIRST
   The last line of the thread should exist in your head before you write the first line.
   A strong closing gives direction to the entire narrative.

4. THEN WRITE THE HOOK
   A hook is not an intro. A hook is a promise to the reader about the journey they're about to take.
   It must be specific, not generic. It must feel like a conversation, not an announcement.

━━━ HOW TO WRITE EACH TWEET ━━━

Each tweet is a self-contained narrative unit that is also part of a larger arc:

FIRST LINE OF TWEET: open with a fact, observation, or question that makes people pause.
Not: "This project has some interesting features..."
But: "The problem isn't the lack of liquidity. The problem is who actually controls that liquidity."

MIDDLE OF TWEET: give one layer of depth. Bullets if it's genuinely a list. Prose if it flows better.

LAST LINE OF TWEET: this is the most important part.
Must be short. Must feel like a conclusion discovered, not declared.
"And that changes everything." ← too generic
"Selling, for once, isn't an exit." ← specific, unexpected, memorable

━━━ WHAT IS FORBIDDEN (non-negotiable) ━━━

✗ Fabricating data, numbers, or quotes not present in the research
✗ Words: "amazing", "revolutionary", "game-changing", "groundbreaking", "innovative"
   → Show it through concrete mechanisms, don't label it with adjectives
✗ Sentences the reader can predict before they finish reading
✗ Triumphant closings without any acknowledgment of risk or uncertainty
✗ More than 2 emojis per tweet

━━━ FORMAT RULES ━━━

- Numbering: "1/N" — decide the total first, then write all tweets
- Min 7, max 12 tweets
- Tweet 1 ends with: "Stay w me 🧵..." or a natural variation
- Last tweet: honest reflection + website URL + @handle if available
- Each paragraph within a tweet is separated by \\n\\n inside the JSON string

RETURN ONLY VALID JSON — no text before or after the curly braces.

⚠️  CRITICAL JSON RULES — MUST BE FOLLOWED:
Use \\n (two characters: backslash + n) for line breaks inside JSON strings.
DO NOT use literal enter/newline inside strings — it will break the JSON.

WRONG  (literal newline, broken JSON):
  "tweets": ["1/9
First sentence

Second sentence"]

CORRECT  (escaped, valid JSON):
  "tweets": ["1/9\\nFirst sentence\\n\\nSecond sentence"]

Template:
{{
  "project_name": "Project Name",
  "project_archetype": "the_rebel / the_frontier / etc",
  "twitter_handle": "@handle_or_empty",
  "total_tweets": 9,
  "tweets": [
    "1/9\\nStrong opening line.\\n\\nSecond paragraph.\\n\\nShort closer.",
    "2/9\\nTweet two content.\\n\\nDeeper detail.",
    "3/9\\nAnd so on until the last tweet..."
  ]
}}
"""

    # ── Main generate function ────────────────────────────────────
    async def generate_thread(self, url: str, twitter_handle: str = "",
                               lang: str = "english",
                               provider: str = "groq") -> dict:
        try:
            # ── Step 1: Scrape website ──────────────────────────────
            logger.info(f"Scraping website: {url}")
            web_data = await self.web_scraper.deep_scrape(url)

            if not web_data.get("pages"):
                return {"success": False, "error": "Could not access the website."}

            web_research = self.compile_web_research(web_data)

            if len(web_research) < 150:
                return {"success": False,
                        "error": "Too little content found. Try the project's docs/whitepaper URL."}

            # ── Step 2: Detect/Scrape Twitter ───────────────────────
            # Priority: user-provided handle > auto-detected from website
            detected_handle = web_data.get("twitter_handle", "")
            final_handle = twitter_handle or detected_handle or ""

            twitter_research = ""
            twitter_data = {}

            if final_handle:
                logger.info(f"Scraping Twitter: @{final_handle}")
                twitter_data = await self.twitter_scraper.research_account(final_handle)
                if twitter_data.get("success"):
                    twitter_research = self.twitter_scraper.format_for_research(twitter_data)
                    logger.info(f"Twitter research OK: {len(twitter_research)} chars")
                else:
                    logger.warning(f"Twitter scrape failed for @{final_handle}")
                    twitter_research = f"[Twitter @{final_handle}: data could not be accessed at this time]"
            else:
                logger.info("No Twitter handle — website only mode")

            # ── Step 3: Brand DNA Analysis ─────────────────────────
            brand_profile = ""
            try:
                main_page = web_data["pages"][0]
                main_html = main_page.get("raw_html", "")
                if main_html:
                    logger.info("Analyzing brand DNA...")
                    brand_data = await self.brand_analyzer.analyze(
                        url, main_html,
                        twitter_data if twitter_data.get("success") else None
                    )
                    brand_profile = self.brand_analyzer.format_for_prompt(brand_data)
                    logger.info(f"Brand: archetype={brand_data.get('project_archetype')}, "
                               f"vibe={brand_data.get('dominant_vibe')}, "
                               f"mood={brand_data.get('color_mood')}")
            except Exception as e:
                logger.warning(f"Brand analysis failed (non-fatal): {e}")

            # ── Step 4: Generate with AI provider ────────────────
            logger.info(f"Generating with provider: {provider}")
            prompt = self.create_prompt(
                web_research, twitter_research, url, final_handle, lang, brand_profile
            )

            system_prompt = (
                "You are a writer with a distinctive voice — "
                "thinking like an investigative journalist, writing like an essayist who cares about craft. "
                "Every sentence must be able to answer: why does this sentence need to exist? "
                "Never fabricate data. "
                "Return ONLY valid JSON — no text before { or after }."
            )

            raw, provider_used = await generate_with_fallback(
                prompt=prompt,
                system=system_prompt,
                preferred_provider=provider,
            )
            data = self._parse_json(raw)

            if not data or "tweets" not in data:
                logger.error(f"JSON parse failed. Raw: {raw[:300]}")
                return {"success": False, "error": "Failed to parse AI response. Please try again."}

            tweets = data["tweets"]
            total = len(tweets)

            # Fix numbering
            fixed = []
            for i, t in enumerate(tweets, 1):
                body = re.sub(r"^\d+/\d+\s*\n?", "", t).strip()
                fixed.append(f"{i}/{total}\n{body}")

            provider_info = PROVIDERS.get(provider_used, {})
            return {
                "success": True,
                "project_name": data.get("project_name", self._domain(url)),
                "twitter_handle": final_handle,
                "twitter_success": twitter_data.get("success", False),
                "twitter_source": twitter_data.get("source", ""),
                "tweets": fixed,
                "tweet_count": total,
                "url": url,
                "provider_used": provider_used,
                "provider_name": provider_info.get("name", provider_used),
                "provider_emoji": provider_info.get("emoji", "🤖"),
                "provider_model": provider_info.get("model", ""),
                "brand_analyzed": bool(brand_profile),
            }

        except Exception as e:
            logger.error(f"generate_thread error: {e}", exc_info=True)
            return {"success": False, "error": str(e)}

    def _parse_json(self, raw: str) -> Optional[dict]:
        """
        Robust JSON parser with a layered repair pipeline.
        Handles various LLM output quirks:
        - Literal newlines inside string values (most common bug)
        - Markdown code fences (```json ... ```)
        - Preamble text before {
        - Trailing commas, comments, stray characters
        """
        candidates = [raw]

        # Strip markdown fences
        stripped = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()
        if stripped != raw:
            candidates.append(stripped)

        # Extract JSON block from surrounding text
        m = re.search(r"\{[\s\S]*\}", raw)
        if m:
            candidates.append(m.group())

        for candidate in candidates:
            # Try direct parse
            try:
                r = json.loads(candidate)
                if r and isinstance(r, dict):
                    return r
            except json.JSONDecodeError:
                pass

            # Repair: escape literal newlines inside string values
            repaired = self._repair_json_strings(candidate)
            try:
                r = json.loads(repaired)
                if r and isinstance(r, dict):
                    logger.info("JSON repaired via string escape fix")
                    return r
            except json.JSONDecodeError:
                pass

            # Repair: remove trailing commas before } or ]
            no_trailing = re.sub(r",\s*([}\]])", r"\1", repaired)
            try:
                r = json.loads(no_trailing)
                if r and isinstance(r, dict):
                    logger.info("JSON repaired via trailing comma removal")
                    return r
            except json.JSONDecodeError:
                pass

        # Last resort: manual tweet extraction if JSON is too broken
        return self._extract_tweets_manually(raw)

    def _repair_json_strings(self, raw: str) -> str:
        """
        Escape literal control characters inside JSON string values.
        LLMs often write literal newlines instead of \\n inside JSON strings.
        """
        result = []
        in_string = False
        i = 0
        while i < len(raw):
            c = raw[i]
            # Toggle string state on unescaped quote
            if c == '"' and (i == 0 or raw[i-1] != '\\'):
                in_string = not in_string
                result.append(c)
            elif in_string:
                # Escape control characters that should be escaped
                if c == '\n':
                    result.append('\\n')
                elif c == '\r':
                    result.append('\\r')
                elif c == '\t':
                    result.append('\\t')
                elif ord(c) < 0x20:  # other control characters
                    result.append(f'\\u{ord(c):04x}')
                else:
                    result.append(c)
            else:
                result.append(c)
            i += 1
        return ''.join(result)

    def _extract_tweets_manually(self, raw: str) -> Optional[dict]:
        """
        Last resort: manually extract tweets from raw text
        if JSON is completely unparseable.
        Looks for the pattern "1/N ... 2/N ... etc"
        """
        logger.warning("Falling back to manual tweet extraction")

        # Find project_name
        name_match = re.search(r'"project_name"\s*:\s*"([^"]+)"', raw)
        project_name = name_match.group(1) if name_match else "Unknown Project"

        # Find twitter_handle
        handle_match = re.search(r'"twitter_handle"\s*:\s*"([^"]*)"', raw)
        twitter_handle = handle_match.group(1) if handle_match else ""

        # Find total_tweets first
        total_match = re.search(r'"total_tweets"\s*:\s*(\d+)', raw)
        total = int(total_match.group(1)) if total_match else 10

        # Extract tweet content with regex
        # Pattern: "N/M\n...content..." or "N/M content"
        tweet_pattern = re.compile(
            r'"(\d+/' + str(total) + r'[\s\S]*?)(?="' + r'\d+/' + str(total) + r'|"\s*\])',
            re.MULTILINE
        )
        found = tweet_pattern.findall(raw)

        if not found:
            # Fallback: split by numbering pattern
            parts = re.split(r'(?="?\d+/\d+)', raw)
            found = [p.strip().strip('"').strip() for p in parts if re.match(r'\d+/\d+', p.strip().strip('"'))]

        if found and len(found) >= 3:
            tweets = []
            for t in found:
                # Clean up: remove stray escape chars, trim
                t = t.strip().strip('"').strip()
                t = re.sub(r'\\n', '\n', t)
                t = re.sub(r'\\t', '\t', t)
                if len(t) > 10:
                    tweets.append(t)

            if len(tweets) >= 3:
                logger.info(f"Manual extraction: recovered {len(tweets)} tweets")
                return {
                    "project_name": project_name,
                    "twitter_handle": twitter_handle,
                    "total_tweets": len(tweets),
                    "tweets": tweets,
                }

        return None

    def _domain(self, url: str) -> str:
        netloc = urlparse(url).netloc.replace("www.", "")
        return netloc.split(".")[0].capitalize()
